### ISSUE TITLE
Cannot cast `String` to `Boolean`

### ISSUE THREAD

**Issue by volodya-lombrozo** [objectionary/eoc#104]
I'm trying to dataize the next program:
```eo
+alias org.eolang.txt.sprintf

[n] > loop
  cage 0 > index
  seq > @
    sprintf
      "%s"
      n
```

In order to do so I use `eoc dataize loop 1` command.
**Expected**: program prints "1" to the console.
**Actual**: 
```sh
EO version is 0.28.11
EO objects registered in /Users/lombrozo/Workspace/EOlang/Research/DeMu/samples/cage/.eoc/eo-foreign.json
EO version is 0.28.11
EO program assembled in /Users/lombrozo/Workspace/EOlang/Research/DeMu/samples/cage/.eoc
EO version is 0.28.11
Java sources generated in /Users/lombrozo/Workspace/EOlang/Research/DeMu/samples/cage/.eoc/generated-sources
EO version is 0.28.11
Java .class files compiled into /Users/lombrozo/Workspace/EOlang/Research/DeMu/samples/cage/.eoc
EO version is 0.28.11
Executable JAR created at /Users/lombrozo/Workspace/EOlang/Research/DeMu/samples/cage/.eoc/eoc.jar
Exception in thread "main" java.lang.ClassCastException: Cannot cast java.lang.String to java.lang.Boolean
	at java.base/java.lang.Class.cast(Class.java:3605)
	at org.eolang.Dataized.take(Dataized.java:127)
	at org.eolang.Main.run(Main.java:190)
	at org.eolang.Main.main(Main.java:98)
```

I don't understand where I'm using `Boolean` and how to fix the program to make it work.

**Comment by volodya-lombrozo** [comment]
It works, thank you.
