### ISSUE TITLE
eoc link error: "Cannot find module 'node:util'"

### ISSUE THREAD

**Issue by OlesiaSub** [objectionary/eoc#34]
I have just installed eolang on ubuntu (v. 22), but I cannot do anything because `eoc link` fails with the following message:
```
internal/modules/cjs/loader.js:818
  throw err;
  ^

Error: Cannot find module 'node:util'
Require stack:
- /usr/local/lib/node_modules/eolang/src/tinted-console.js
- /usr/local/lib/node_modules/eolang/src/eoc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/eolang/src/tinted-console.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/eolang/src/tinted-console.js',
    '/usr/local/lib/node_modules/eolang/src/eoc.js'
  ]
}

```
I've already tried removing node_modules directory and reinstalling eo, but got the same result.

Here is the output of `sudo npm install -g eolang` in case you need it

```
added 6 packages, and audited 7 packages in 1s

1 package is looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

**Comment by OlesiaSub** [comment]
I solved it by installing npm using nvm instead of apt
