### ISSUE TITLE
Can't run `phi` with `--alone`

### ISSUE THREAD

**Issue by maxonfjvipon** [objectionary/eoc#360]
I tried to run `eoc --alone --verbose --parser=0.40.3 --home-tag=master phi` and here's what I've got:
```
Book-Pro:unphi maxonfjvipon$ eoc --alone --verbose --parser=0.40.3 --home-tag=master phi
Debug output is turned ON
EO parser 0.39.2; use the --latest flag if you need a freshier one
The "paths[1]" argument must be of type string. Received undefined
TypeError [ERR_INVALID_ARG_TYPE]: The "paths[1]" argument must be of type string. Received undefined
    at Object.resolve (node:path:1168:7)
    at module.exports [as phi] (/opt/homebrew/lib/node_modules/eolang/src/commands/phi.js:38:22)
    at Command.<anonymous> (/opt/homebrew/lib/node_modules/eolang/src/eoc.js:213:14)
    at Command.listener [as _actionHandler] (/opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:542:17)
    at /opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:1502:14
    at Command._chainOrCall (/opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:1386:12)
    at Command._parseCommand (/opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:1501:27)
    at /opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:1265:27
    at Command._chainOrCall (/opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:1386:12)
    at Command._dispatchSubcommand (/opt/homebrew/lib/node_modules/eolang/node_modules/commander/lib/command.js:1261:25)
```

It happens because [here](https://github.com/objectionary/eoc/blob/19de5b1b9fd14b23ffb3fa88eec4f33b50b7c011/src/eoc.js#L213) instead of `coms().phi(program.opts());` it must be `coms().phi({...program.opts(), ...str});`

The same problem with all other commands in `--alone` mode
@yegor256 please take a look

**Comment by yegor256** [comment]
@rultor release, tag is `0.23.0`

**Comment by yegor256** [comment]
@maxonfjvipon version 0.23.0 released, with a fix
