### ISSUE TITLE
semver failure when using `1.0-SNAPSHOT`

### ISSUE THREAD

**Issue by yegor256** [objectionary/eoc#424]
I'm getting this when I use `--parser=1.0-SNAPSHOT`:

```
/opt/homebrew/lib/node_modules/eolang/node_modules/semver/classes/semver.js:38
      throw new TypeError(`Invalid Version: ${version}`)
            ^

TypeError: Invalid Version: 1.0-SNAPSHOT
    at new SemVer (/opt/homebrew/lib/node_modules/eolang/node_modules/semver/classes/semver.js:38:13)
    at compare (/opt/homebrew/lib/node_modules/eolang/node_modules/semver/functions/compare.js:3:3)
    at Object.gte (/opt/homebrew/lib/node_modules/eolang/node_modules/semver/functions/gte.js:2:30)
    at module.exports [as lint] (/opt/homebrew/lib/node_modules/eolang/src/commands/lint.js:39:14)
    at /opt/homebrew/lib/node_modules/eolang/src/eoc.js:341:29
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

**Comment by yegor256** [comment]
@rultor release, tag is `0.27.1`
