### ISSUE TITLE
"Error: Cannot find module 'node:util'" when runnning 'eoc dataize hello'

### ISSUE THREAD

**Issue by EduardoFernandes1410** [objectionary/eoc#78]
I'm trying to run the hello.eo program from README. When I execute

`eoc dataize hello`

I get the following error:

```
internal/modules/cjs/loader.js:818
  throw err;
  ^
Error: Cannot find module 'node:util'
Require stack:
- /usr/local/lib/node_modules/eolang/src/tinted-console.js
- /usr/local/lib/node_modules/eolang/src/eoc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/eolang/src/tinted-console.js:26:14)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/usr/local/lib/node_modules/eolang/src/tinted-console.js',
    '/usr/local/lib/node_modules/eolang/src/eoc.js'
  ]
}
```

npm version: 8.5.1
node version: 12.22.9
OS: ubuntu 22.04

**Comment by devgru** [comment]
@EduardoFernandes1410 sadly, this won't work on older node versions.

`node:` prefix was introduced in v16.0.0 and v14.18.0 versions. Upgrading your `nodejs` package could help.

**Comment by EduardoFernandes1410** [comment]
Thank you, that did it!
